[package]
name = "softambe-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "softambe"

[[bin]]
name = "softambeserver"
path = "src/bin/softambeserver.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.6.1", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1", features = ["net", "rt", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
cc = "1.2.61"
cmake = "0.1"
