#!/bin/sh
# Daily fetch of the RadioID.net subscriber database.  Atomic update.
set -eu

URL="https://radioid.net/static/user.csv"
DEST_DIR="/var/lib/asl-dmr-bridge/subscribers"
DEST="${DEST_DIR}/user.csv"

TMP="$(mktemp "${DEST_DIR}/user.csv.XXXXXX")"
trap 'rm -f "${TMP}"' EXIT

wget --quiet --tries=3 --timeout=30 -O "${TMP}" "${URL}"
chmod 0644 "${TMP}"
mv -f "${TMP}" "${DEST}"
trap - EXIT
